'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ChromeMenu

    
    '''<summary>
    '''menuitem5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    <System.ComponentModel.Description("menuitem5 control.")> _
    Protected WithEvents menuitem5 As Global.DTIAdminPanel.MenuItem

    
    '''<summary>
    '''menuitem6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    <System.ComponentModel.Description("menuitem6 control.")> _
    Protected WithEvents menuitem6 As Global.DTIAdminPanel.MenuItem
End Class
