'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ucVideo

    
    '''<summary>
    '''lbDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    <System.ComponentModel.Description("lbDelete control.")> _
    Protected WithEvents lbDelete As Global.System.Web.UI.WebControls.Button

    
    '''<summary>
    '''divImg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    <System.ComponentModel.Description("divImg control.")> _
    Protected WithEvents divImg As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    
    '''<summary>
    '''lkImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    <System.ComponentModel.Description("lkImage control.")> _
    Protected WithEvents lkImage As Global.System.Web.UI.HtmlControls.HtmlAnchor

    
    '''<summary>
    '''LazyImgLoad1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    <System.ComponentModel.Description("LazyImgLoad1 control.")> _
    Protected WithEvents LazyImgLoad1 As Global.JqueryUIControls.LazyImgLoad

    
    '''<summary>
    '''litButtons control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    <System.ComponentModel.Description("litButtons control.")> _
    Protected WithEvents litButtons As Global.System.Web.UI.WebControls.Literal
End Class
