'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ChangePasswordControl

    
    '''<summary>
    '''tbpass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    <System.ComponentModel.Description("tbpass control.")> _
    Protected WithEvents tbpass As Global.System.Web.UI.WebControls.TextBox

    
    '''<summary>
    '''valReq control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    <System.ComponentModel.Description("valReq control.")> _
    Protected WithEvents valReq As Global.System.Web.UI.WebControls.RequiredFieldValidator

    
    '''<summary>
    '''tbConfirm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    <System.ComponentModel.Description("tbConfirm control.")> _
    Protected WithEvents tbConfirm As Global.System.Web.UI.WebControls.TextBox

    
    '''<summary>
    '''valComp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    <System.ComponentModel.Description("valComp control.")> _
    Protected WithEvents valComp As Global.System.Web.UI.WebControls.CompareValidator

    
    '''<summary>
    '''btnChange control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    <System.ComponentModel.Description("btnChange control.")> _
    Protected WithEvents btnChange As Global.System.Web.UI.WebControls.Button

    
    '''<summary>
    '''InfoDiv1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    <System.ComponentModel.Description("InfoDiv1 control.")> _
    Protected WithEvents InfoDiv1 As Global.JqueryUIControls.InfoDiv
End Class
