'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class VideoInsertOptions
    
    '''<summary>
    '''hlInsertVideo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlInsertVideo As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''hlInsertVideoThumb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlInsertVideoThumb As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''hlDeleteVideo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlDeleteVideo As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''hsEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hsEdit As Global.HighslideControls.Highslider
End Class
