'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class DTISiteMapEditor

    
    '''<summary>
    '''tlMenuItems control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    <System.ComponentModel.Description("tlMenuItems control.")> _
    Protected WithEvents tlMenuItems As Global.DTIMiniControls.TreeList

    
    '''<summary>
    '''tlPages control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    <System.ComponentModel.Description("tlPages control.")> _
    Protected WithEvents tlPages As Global.DTIMiniControls.TreeList

    
    '''<summary>
    '''btnSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    <System.ComponentModel.Description("btnSave control.")> _
    Protected WithEvents btnSave As Global.System.Web.UI.WebControls.Button
End Class
