'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4927
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''Gallery class.
'''</summary>
'''<remarks>
'''Auto-generated class.
'''</remarks>
Partial Public Class Gallery

    '''<summary>
    '''AjaxSeverConrol1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AjaxSeverConrol1 As Global.DTIAjax.ajaxSeverConrol

    '''<summary>
    '''pnlGalleryHolder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlGalleryHolder As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''pnlSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlSearch As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''freezePanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents freezePanel As Global.DTIMiniControls.FreezeIt

    '''<summary>
    '''imgWait control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgWait As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''pnlThumbHolder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlThumbHolder As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''pnlUploadLinks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlUploadLinks As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Gallery_Button_Div control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Gallery_Button_Div As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''btnGalleryFirst control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnGalleryFirst As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''btnGalleryBack control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnGalleryBack As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''tbGalleryPage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbGalleryPage As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblSlash control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSlash As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblGalleryTotalPages control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGalleryTotalPages As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnGalleryPage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnGalleryPage As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''btnGalleryFwd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnGalleryFwd As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''btnGalleryLast control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnGalleryLast As Global.System.Web.UI.WebControls.ImageButton
End Class
