'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class EditImageUserControl

    
    '''<summary>
    '''pnlEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    <System.ComponentModel.Description("pnlEdit control.")> _
    Protected WithEvents pnlEdit As Global.System.Web.UI.WebControls.Panel

    
    '''<summary>
    '''imgPreviewEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    <System.ComponentModel.Description("imgPreviewEdit control.")> _
    Protected WithEvents imgPreviewEdit As Global.HighslideControls.Highslider

    
    '''<summary>
    '''lblSize control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    <System.ComponentModel.Description("lblSize control.")> _
    Protected WithEvents lblSize As Global.System.Web.UI.WebControls.Label
End Class
