'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class TagsUC

    
    '''<summary>
    '''lblCurrTags control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    <System.ComponentModel.Description("lblCurrTags control.")> _
    Protected WithEvents lblCurrTags As Global.System.Web.UI.WebControls.Label

    
    '''<summary>
    '''DTICurrTags control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    <System.ComponentModel.Description("DTICurrTags control.")> _
    Protected WithEvents DTICurrTags As Global.System.Web.UI.WebControls.Panel

    
    '''<summary>
    '''hfTags control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    <System.ComponentModel.Description("hfTags control.")> _
    Protected WithEvents hfTags As Global.System.Web.UI.WebControls.HiddenField

    
    '''<summary>
    '''DTIPopularTagHolder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    <System.ComponentModel.Description("DTIPopularTagHolder control.")> _
    Protected WithEvents DTIPopularTagHolder As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    
    '''<summary>
    '''lblPopularTags control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    <System.ComponentModel.Description("lblPopularTags control.")> _
    Protected WithEvents lblPopularTags As Global.System.Web.UI.WebControls.Label

    
    '''<summary>
    '''DTIPopularTags control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    <System.ComponentModel.Description("DTIPopularTags control.")> _
    Protected WithEvents DTIPopularTags As Global.System.Web.UI.WebControls.Panel

    
    '''<summary>
    '''lblAddTags control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    <System.ComponentModel.Description("lblAddTags control.")> _
    Protected WithEvents lblAddTags As Global.System.Web.UI.WebControls.Label

    
    '''<summary>
    '''tbNewTags control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    <System.ComponentModel.Description("tbNewTags control.")> _
    Protected WithEvents tbNewTags As Global.System.Web.UI.WebControls.TextBox

    
    '''<summary>
    '''btnAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    <System.ComponentModel.Description("btnAdd control.")> _
    Protected WithEvents btnAdd As Global.System.Web.UI.HtmlControls.HtmlInputButton

    
    '''<summary>
    '''btnSubmit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    <System.ComponentModel.Description("btnSubmit control.")> _
    Protected WithEvents btnSubmit As Global.System.Web.UI.WebControls.Button
End Class
