'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3603
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''PageEditControl class.
'''</summary>
'''<remarks>
'''Auto-generated class.
'''</remarks>
Partial Public Class PageEditControl

    '''<summary>
    '''HiddenField1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    <System.ComponentModel.Description("HiddenField1 control.")> _
    Protected WithEvents HiddenField1 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''tbPageName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    <System.ComponentModel.Description("tbPageName control.")> _
    Protected WithEvents tbPageName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    <System.ComponentModel.Description("tbLink control.")> _
    Protected WithEvents tbLink As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    <System.ComponentModel.Description("lbl control.")> _
    Protected WithEvents lbl As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ddlMasterPage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    <System.ComponentModel.Description("ddlMasterPage control.")> _
    Protected WithEvents ddlMasterPage As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''cbAdmin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    <System.ComponentModel.Description("cbAdmin control.")> _
    Protected WithEvents cbAdmin As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cbUsers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    <System.ComponentModel.Description("cbUsers control.")> _
    Protected WithEvents cbUsers As Global.System.Web.UI.WebControls.CheckBox
End Class
