'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3603
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''DTIUploaderUserControl class.
'''</summary>
'''<remarks>
'''Auto-generated class.
'''</remarks>
Partial Public Class DTIUploaderUserControl

    '''<summary>
    '''fileSizeWarning control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    <System.ComponentModel.Description("fileSizeWarning control.")> _
    Protected WithEvents fileSizeWarning As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblFileSizeWarning control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    <System.ComponentModel.Description("lblFileSizeWarning control.")> _
    Protected WithEvents lblFileSizeWarning As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FileSizeLimit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    <System.ComponentModel.Description("FileSizeLimit control.")> _
    Protected WithEvents FileSizeLimit As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''errorMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    <System.ComponentModel.Description("errorMessage control.")> _
    Protected WithEvents errorMessage As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlUploaderHolder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    <System.ComponentModel.Description("pnlUploaderHolder control.")> _
    Protected WithEvents pnlUploaderHolder As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''btnWeb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    <System.ComponentModel.Description("btnWeb control.")> _
    Protected WithEvents btnWeb As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnToggleMode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    <System.ComponentModel.Description("btnToggleMode control.")> _
    Protected WithEvents btnToggleMode As Global.System.Web.UI.WebControls.LinkButton
End Class
