(function(){CKEDITOR.plugins.add("oembed",{requires:["dialog"],lang:"de en fr nl pl ru".split(" "),afterInit:function(b){var c=b.dataProcessor,c=c&&c.dataFilter;b.config.oembed_ShowIframePreview?c._.elements.iframe&&delete c._.elements.iframe:c&&"undefined"==c._.elements.iframe&&c.addRules({elements:{iframe:function(c){return b.createFakeParserElement(c,"cke_iframe","iframe",!0)}}})},init:function(b){function c(a,f,d,e,c,h){jQuery("body").oembed(a,{onEmbed:function(a){var c=new CKEDITOR.dom.element("div");
"string"===typeof a.code?(null!=b.config.oembed_WrapperClass&&c.addClass(b.config.oembed_WrapperClass),a=CKEDITOR.dom.element.createFromHtml(a.code),"IFRAME"==a.$.tagName&&!1===b.config.oembed_ShowIframePreview&&(a=b.createFakeElement(a,"cke_iframe","iframe",!0)),a.appendTo(c),f.insertElement(c),d&&CKEDITOR.dialog.getCurrent().hide()):"string"===typeof a.code[0].outerHTML?(null!=b.config.oembed_WrapperClass&&c.addClass(b.config.oembed_WrapperClass),a=CKEDITOR.dom.element.createFromHtml(a.code[0].outerHTML),
"IFRAME"==a.$.tagName&&!1===b.config.oembed_ShowIframePreview&&(a=b.createFakeElement(a,"cke_iframe","iframe",!0)),a.appendTo(c),f.insertElement(c),d&&CKEDITOR.dialog.getCurrent().hide()):alert(b.lang.oembed.noEmbedCode)},onError:function(a){0<a.indexOf("vimeo.com")?alert(b.lang.oembed.noVimeo):alert(b.lang.oembed.Error)},maxHeight:c,maxWidth:e,useResponsiveResize:h,embedMethod:"editor"})}if(null==b.config.oembed_ShowIframePreview||"undefined"==b.config.oembed_ShowIframePreview)b.config.oembed_ShowIframePreview=
!1;!b.plugins.iframe&&!b.config.oembed_ShowIframePreview&&CKEDITOR.addCss("img.cke_iframe{background-image: url("+CKEDITOR.getUrl(CKEDITOR.plugins.getPath("oembed")+"images/placeholder.png")+");background-position: center center;background-repeat: no-repeat;border: 1px solid #a9a9a9;width: 80px;height: 80px;}");(function(){"undefined"===typeof jQuery?CKEDITOR.scriptLoader.load("http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js",function(){"undefined"===typeof jQuery.fn.oembed&&CKEDITOR.scriptLoader.load(CKEDITOR.getUrl(CKEDITOR.plugins.getPath("oembed")+
"libs/jquery.oembed.min.js"))}):"undefined"===typeof jQuery.fn.oembed&&CKEDITOR.scriptLoader.load(CKEDITOR.getUrl(CKEDITOR.plugins.getPath("oembed")+"libs/jquery.oembed.min.js"))})();CKEDITOR.tools.extend(CKEDITOR.editor.prototype,{oEmbed:function(a,f,d,e){function g(){if(null==f||"undefined"==f)f=null;if(null==d||"undefined"==d)d=null;if(null==e||"undefined"==e)e=!1;c(a,b,!1,f,d,e)}if(1>a.length||0>a.indexOf("http"))return alert(b.lang.oembed.invalidUrl),!1;"undefined"===typeof jQuery.fn.oembed?
CKEDITOR.scriptLoader.load(CKEDITOR.getUrl(CKEDITOR.plugins.getPath("oembed")+"libs/jquery.oembed.min.js"),function(){g()}):g();return!0}});b.addCommand("oembed",new CKEDITOR.dialogCommand("oembed"));b.ui.addButton("oembed",{label:b.lang.oembed.button,command:"oembed",icon:this.path+"images/icon.png"});var k=function(){var a=this.getDialog(),b=this.getValue(),d=a.getContentElement("general","maxSizeBox").getElement(),a=a.getContentElement("general","sizeBox").getElement();"noresize"==b?(d.hide(),
a.hide()):"custom"==b?(d.hide(),a.show()):(d.show(),a.hide())};String.prototype.beginsWith=function(a){return 0===this.indexOf(a)};CKEDITOR.dialog.add("oembed",function(a){return{title:a.lang.oembed.title,minWidth:CKEDITOR.env.ie&&CKEDITOR.env.quirks?568:550,minHeight:155,onShow:function(){var a=this.getContentElement("general","resizeType").getValue(),b=this.getContentElement("general","maxSizeBox").getElement(),c=this.getContentElement("general","sizeBox").getElement();"noresize"==a?(b.hide(),c.hide()):
"custom"==a?(b.hide(),c.show()):(b.show(),c.hide())},onOk:function(){var b=this.getValueOf("general","embedCode"),d=this.getContentElement("general","resizeType").getValue(),e=null,g=null,h=!1,j=this.getParentEditor(),i=this.getContentElement("general","autoCloseDialog").getValue();if(1>b.length||0>b.indexOf("http"))return alert(a.lang.oembed.invalidUrl),!1;"noresize"==d?h=!1:"responsive"==d?(e=this.getContentElement("general","maxWidth").getInputElement().getValue(),g=this.getContentElement("general",
"maxHeight").getInputElement().getValue(),h=!0):"custom"==d&&(e=this.getContentElement("general","width").getInputElement().getValue(),g=this.getContentElement("general","height").getInputElement().getValue(),h=!1);if(0<b.indexOf(";")){b=b.split(";");for(d=0;d<b.length;d++)i=b[d],1<i.length&&i.beginsWith("http")&&c(i,j,!1,e,g,h),d==b.length-1&&CKEDITOR.dialog.getCurrent().hide()}else c(b,j,i,e,g,h);return!1},contents:[{label:a.lang.common.generalTab,id:"general",elements:[{type:"html",id:"oembedHeader",
html:'<div style="white-space:normal;width:500px;padding-bottom:10px">'+a.lang.oembed.pasteUrl+"</div>"},{type:"text",id:"embedCode",focus:function(){this.getElement().focus()},label:a.lang.oembed.url,title:a.lang.oembed.pasteUrl},{type:"hbox",widths:["50%","50%"],children:[{id:"resizeType",type:"select",label:a.lang.oembed.resizeType,"default":"noresize",items:[[a.lang.oembed.noresize,"noresize"],[a.lang.oembed.responsive,"responsive"],[a.lang.oembed.custom,"custom"]],onChange:k},{type:"hbox",id:"maxSizeBox",
widths:["120px","120px"],style:"float:left;position:absolute;left:58%;width:200px",children:[{type:"text",width:"100px",id:"maxWidth","default":null!=a.config.oembed_maxWidth?a.config.oembed_maxWidth:"560",label:a.lang.oembed.maxWidth,title:a.lang.oembed.maxWidthTitle},{type:"text",id:"maxHeight",width:"120px","default":null!=a.config.oembed_maxHeight?a.config.oembed_maxHeight:"315",label:a.lang.oembed.maxHeight,title:a.lang.oembed.maxHeightTitle}]},{type:"hbox",id:"sizeBox",widths:["120px","120px"],
style:"float:left;position:absolute;left:58%;width:200px",children:[{type:"text",id:"width",width:"100px","default":null!=a.config.oembed_maxWidth?a.config.oembed_maxWidth:"560",label:a.lang.oembed.width,title:a.lang.oembed.widthTitle},{type:"text",id:"height",width:"120px","default":null!=a.config.oembed_maxHeight?a.config.oembed_maxHeight:"315",label:a.lang.oembed.height,title:a.lang.oembed.heightTitle}]}]},{type:"checkbox",id:"autoCloseDialog","default":"checked",label:a.lang.oembed.autoClose,
title:a.lang.oembed.autoClose}]}]}})}})})();